### ISSUE TITLE
[Rubocop] Re-enable Metrics/AbcSize

### ISSUE THREAD

**Issue by kylef** [CocoaPods/shared#5]
These we're disabled in 51fe6453e0b15dc38db529bae3ad333140352fa7 to ease upgrading to Rubocop 0.27.0 but we should look into fixing these issues and enabling this rule.

From https://github.com/CocoaPods/Molinillo/commit/87b6784341a98820c628daafa59bc8550d4fbd42#commitcomment-8586155

**Comment by segiddins** [comment]
Closing, I agree with @alloy on this one.
